default:
  image: golang:1.21-bullseye

stages:
  - linter
  - test

lint-via-tool:
  stage: linter
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.55.2
    - ./bin/golangci-lint run --enable promlinter --enable tparallel  --disable unused ./...

unit-tests:
  stage: test
  coverage: '/coverage: \d+.\d+% of statements/'
  script:
    - make tests
