version: "2.19"

services:
  database:
    container_name: ${DB_CONTAINER}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${API_CONTAINER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  server:
    container_name: ${API_CONTAINER}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.server
    ports:
      - 8080:8080

volumes:
  db:
