version: "2.23"

services:
  server:
    container_name: ${API_CONTAINER}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ../.:/app
    command: sleep infinity
    ports:
      - 8080:8080
    depends_on:
      mysql-db:
        condition: service_healthy

  # mysql-db:
  #   container_name: ${MYSQL_CONTAINER}
  #   image: mysql:8.0
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
  #     - MYSQL_HOST=${MYSQL_CONTAINER}
  #     - MYSQL_DATABASE=${MYSQL_DATABASE}
  #   volumes:
  #     - db:/var/lib/mysql
  #   healthcheck:
  #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  #     interval: 5s
  #     retries: 10
  
  postgres-db:
    container_name: ${POSTGRESQL_CONTAINER}
    image: postgres:16.2-bullseye
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRESQL_DB}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  clickhouse-db:
    container_name: ${CLICKHOUSE_CONTAINER}
    image: clickhouse/clickhouse-server:23-alpine
    restart: always
    ports:
      - ${CLICKHOUSE_PORT}:${CLICKHOUSE_PORT}/tcp
      - 9000:9000/tcp
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DATABASE}
      - CLICKHOUSE_USER=${CLICKHOUSE_USERNAME}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse-data:/var/log/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server/

  cache:
    container_name: ${REDIS_CONTAINER}
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

volumes:
  db:
  clickhouse-data:
  clickhouse-logs:
  redis-data:
  postgres-data:
