with-expecter: true
outpkg: mocks
dir: "internal/mocks/{{.PackageName}}"
mockname: "{{.InterfaceName}}"
packages:
  user-management/internal/auth:
    interfaces:
      Token:
      Password:
  user-management/internal/controllers:
    config:
    interfaces:
      Context:
        config:
  user-management/internal/models:
    interfaces:
      UserModel:
  user-management/internal/models/repo:
    interfaces:
      UserRepository:
