with-expecter: true
outpkg: mocks
dir: "internal/mocks/{{.PackageName}}"
mockname: "{{.InterfaceName}}"
packages:
  a-article/internal/auth:
    interfaces:
      Token:
      Cryptor:
  a-article/internal/controllers:
    config:
    interfaces:
      Context:
        config:
  a-article/internal/gateways:
    interfaces:
      CacheStore:
      Serializer:
  a-article/internal/models:
    interfaces:
      UserModel:
      ArticleModel:
  a-article/internal/models/repo:
    interfaces:
      UserRepository:
      ArticleRepository:
  a-article/internal/mailing:
    interfaces:
      Mailman:
