global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "a-article-backend-server"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "server:8080"
  
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "node_exporter:9100"
