// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CacheStore is an autogenerated mock type for the CacheStore type
type CacheStore struct {
	mock.Mock
}

type CacheStore_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheStore) EXPECT() *CacheStore_Expecter {
	return &CacheStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key, value
func (_m *CacheStore) Get(key string, value interface{}) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
//   - value interface{}
func (_e *CacheStore_Expecter) Get(key interface{}, value interface{}) *CacheStore_Get_Call {
	return &CacheStore_Get_Call{Call: _e.mock.On("Get", key, value)}
}

func (_c *CacheStore_Get_Call) Run(run func(key string, value interface{})) *CacheStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *CacheStore_Get_Call) Return(_a0 error) *CacheStore_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheStore_Get_Call) RunAndReturn(run func(string, interface{}) error) *CacheStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *CacheStore) Set(key string, value interface{}) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CacheStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type CacheStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value interface{}
func (_e *CacheStore_Expecter) Set(key interface{}, value interface{}) *CacheStore_Set_Call {
	return &CacheStore_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *CacheStore_Set_Call) Run(run func(key string, value interface{})) *CacheStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(interface{}))
	})
	return _c
}

func (_c *CacheStore_Set_Call) Return(_a0 error) *CacheStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CacheStore_Set_Call) RunAndReturn(run func(string, interface{}) error) *CacheStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewCacheStore creates a new instance of CacheStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheStore {
	mock := &CacheStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
